image: "python:3.8"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - linting
  - behave

  #defines the job in Static Analysis
pylint:
  stage: linting
  allow_failure: true
  script:
  - pylint *.py features/*.py


behave:
  stage: behave
  variables:
    DRIVER: headless
    SELENIUM: http://firefox:4444/wd/hub
  artifacts:
    when: always
    reports:
      junit: reports/*.xml
  services:
  - name: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20201009
    alias: firefox
  script:
  - behave features/article.feature --junit --junit-directory=reports