image: "python:3.8"

stages:
  - linting
  - behave
  - package

  #defines the job in Static Analysis
pylint:
  stage: linting
  allow_failure: true
  before_script:
    - pip3 install -r requirements.txt
  script:
    - pylint *.py features/*.py

behave-article:
  stage: behave
  variables:
    DRIVER: headless
    SELENIUM: http://firefox:4444/wd/hub
  artifacts:
    when: always
    reports:
      junit: reports/*.xml
  services:
    - name: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20201009
      alias: firefox
  allow_failure: true
  before_script:
    - pip3 install -r requirements.txt
  script:
    - behave features/article.feature --junit --junit-directory=reports

behave-about:
  stage: behave
  image: selenium/standalone-firefox:4.0.0-alpha-7-prerelease-20201009
  artifacts:
    when: always
    reports:
      junit: reports/*.xml
  before_script:
    - sudo apt-get update -q
    - sudo apt-get install python3-pip -y -q
    - python3 --version
    - sudo pip3 install -r requirements.txt
  script:
    - behave features/about_page.feature --junit --junit-directory=reports

wheel:
  stage: package
  before_script:
    - pip3 install -r requirements.txt
    - pip3 wheel -r requirements.txt
  script:
    - pip3 wheel .
  artifacts:
    expire_in: 5 days
    paths:
      - dist/*.whl3